buildscript {
    repositories {
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:3.5.16"
        classpath "de.thetaphi:forbiddenapis:3.10"
        classpath "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.6.1"
        classpath "com.gorylenko.gradle-git-properties:gradle-git-properties:2.5.4"
        classpath "dev.yumi:yumi-gradle-licenser:4.0.0"
    }
}

final int requiredJavaMajorVersion = 17
final def requiredJavaVersion =
        JavaVersion.toVersion(requiredJavaMajorVersion)

if (JavaVersion.current() < requiredJavaVersion) {
    throw new RuntimeException("This build requires Java " + requiredJavaVersion + "! https://adoptium.net/temurin/releases/")
}

// This defines the Gradle version to be used by this build.
// The wrapper task can be executed with 'gradle wrapper'.
// It creates the 'gradlew'/'gradlew.bat' files, as well as
// required stub files in the 'gradle' directory.
//
// Using those scripts ensures that the correct Gradle version
// is used (and downloaded automatically).
wrapper {
    gradleVersion = '9.7.1'
}

// https://github.com/kt3k/coveralls-gradle-plugin

// the block below configures all projects, i.e. the rootProject
// and all subprojects
allprojects {
    apply plugin: 'project-reports'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    apply plugin: 'jacoco'
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'dev.yumi.gradle.licenser'

    group = 'org.adealsystems'
    version = '0.52.0'
    def prereleaseIdentifier = System.properties.'prerelease'
    if (prereleaseIdentifier) {
        version = version + '-' + prereleaseIdentifier
    } else if (!System.properties.'release') {
        version = version + '-SNAPSHOT'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(requiredJavaMajorVersion)
        }
    }

    jacoco {
        toolVersion = '0.8.15'
    }

    repositories {
        mavenCentral()
    }

    def compilerArgs = ['-Xlint:all']
    tasks.withType(JavaCompile) {
        options.release = requiredJavaMajorVersion
        options.encoding = 'UTF-8'
        options.debug = true // default, but let's be explicit
        options.compilerArgs = compilerArgs
    }
    tasks.withType(GroovyCompile) {
        options.release = requiredJavaMajorVersion
        options.encoding = 'UTF-8'
        options.debug = true // default, but let's be explicit
        options.compilerArgs = compilerArgs
    }
    tasks.withType(Javadoc) {
        options.optionFiles << rootProject.file('config/javadoc.options')
        // it's actually --release but one - is added automatically. *eyeroll*
        options.addStringOption('-release', "" + requiredJavaMajorVersion)
        options.addBooleanOption('Xdoclint:all,-missing', true)
    }


    // https://github.com/YumiProject/yumi-gradle-licenser/issues/15
    license {
        rule(rootProject.file('license_header.txt'))

        include("**/*.java")
        include("**/*.groovy")
        exclude("**/*.properties")
    }

    // the tasks to be executed if no tasks are given explicitly.
    defaultTasks 'build', 'checkLicenses'
}

// the block below configures all subprojects, i.e. the rootProject
// is excluded
subprojects {
    apply plugin: 'java-library'
    apply plugin: 'groovy'
    apply plugin: 'de.thetaphi.forbiddenapis'
    apply plugin: 'checkstyle'
    apply plugin: 'pmd'


    java {
        withJavadocJar()
        withSourcesJar()
    }

    checkstyle {
        configFile = rootProject.file('config/checkstyle/checkstyle.xml')
        configProperties = [
                'configDir': rootProject.file('config/checkstyle'),
                'baseDir'  : rootDir,
        ]
        toolVersion = '12.3.1' // requires Java 17
        //toolVersion = '13.10.0' // TODO: requires Java 21 - upgrade
        //ignoreFailures = true
    }

    pmd {
        ruleSetFiles = files(rootProject.file('config/pmd/ruleSet.xml'))
        ruleSets = []
        toolVersion = '7.26.0'
        incrementalAnalysis = true
        //ignoreFailures = true
    }

    forbiddenApis {
        bundledSignatures = [
                'jdk-unsafe',
                'jdk-deprecated',
                'jdk-internal',
                'jdk-non-portable',
                //'jdk-system-out',
                'jdk-reflection',
                //'commons-io-unsafe-2.5',
        ]
        ignoreFailures = false
        //failOnUnresolvableSignatures = false
    }

    jacocoTestReport {
        additionalSourceDirs.from(files(sourceSets.main.allSource.srcDirs))
        sourceDirectories.from(files(sourceSets.main.allSource.srcDirs))
        classDirectories.from(files(sourceSets.main.output))
        reports {
            html.required = true
            xml.required = true
            csv.required = false
        }
    }

    // global exclude of "bad" dependencies
    configurations {
        all*.exclude group: 'commons-logging', module: 'commons-logging'
        all*.exclude group: 'org.codehaus.groovy', module: 'groovy-all'
    }

    test {
        useJUnitPlatform()
    }

    // this gives all subprojects a default set of test dependencies
    dependencies {
        implementation rootProject.libs.slf4j.api

        testImplementation rootProject.libs.byte.buddy
        testImplementation rootProject.libs.groovy.core
        testImplementation rootProject.libs.groovy.nio
        testImplementation rootProject.libs.spock.core
        testImplementation rootProject.libs.junit.jupiter.api
        testImplementation rootProject.libs.logback.classic

        testRuntimeOnly rootProject.libs.objenesis
        testRuntimeOnly rootProject.libs.junit.platform.launcher
        testRuntimeOnly rootProject.libs.jcl.over.slf4j
    }
}

configure(subprojects
        - project(':org.adealsystems.platform.spark.example')
        - project(':org.adealsystems.platform.spark.config.example')
        - project(':org.adealsystems.platform.spark.app.example')
) {
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    ext.isReleaseVersion = !version.endsWith("-SNAPSHOT")
    project.description = project.name

    publishing {
        repositories {
            maven {
//                def releaseRepo = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
//                def snapshotRepo = "https://oss.sonatype.org/content/repositories/snapshots/"
                def releaseRepo = "http://nexus.adeal-systems.com:8081/repository/maven-releases"
                def snapshotRepo = "http://nexus.adeal-systems.com:8081/repository/maven-mixed"
                url = isReleaseVersion ? releaseRepo : snapshotRepo
                allowInsecureProtocol = true
                credentials {
//                    username = findProperty('sonatypeUsername')
//                    password = findProperty('sonatypePassword')
                    username = findProperty('nexusUsername')
                    password = findProperty('nexusPassword')
                }
            }
        }

        publications {
            mavenJava(MavenPublication) {
                afterEvaluate {
                    pom {
                        groupId = 'org.adealsystems'
                        name = project.name
                        description = project.description
                        url = 'https://github.com/adealsystems/platform/'
                        from components.java
                        licenses {
                            license {
                                name = 'The Apache License, Version 2.0'
                                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                            }
                        }
                        scm {
                            connection = 'scm:git:git@github.com:adealsystems/platform.git'
                            developerConnection = 'scm:git:git@github.com:adealsystems/platform.git'
                            url = 'https://github.com/adealsystems/platform/'
                        }
                        developers {
                            developer {
                                id = 'huxi'
                                name = 'Joern Huxhorn'
                                email = 'joern.huxhorn@adeal-systems.com'
                            }
                            developer {
                                id = 'vlad'
                                name = 'Vlad Satanovski'
                                email = 'vlad.satanovski@adeal-systems.com'
                            }
                        }
                    }
                }
            }
        }
    }

    signing {
        // signs jar, source und javadoc
        sign publishing.publications.mavenJava
    }

    tasks.withType(Sign) {
        onlyIf { isReleaseVersion }
    }

}


// source: https://gist.github.com/aalmiray/e6f54aa4b3803be0bcac
task jacocoRootReport(type: org.gradle.testing.jacoco.tasks.JacocoReport) {
    dependsOn = subprojects.jacocoTestReport
    dependsOn = subprojects.test
    additionalSourceDirs.setFrom(files(subprojects.sourceSets.main.allSource.srcDirs))
    sourceDirectories.setFrom(files(subprojects.sourceSets.main.allSource.srcDirs))
    classDirectories.setFrom(files(subprojects.sourceSets.main.output))
    executionData.setFrom(fileTree(dir: "${rootProject.projectDir}", includes: ['**/build/jacoco/*.exec']))
    reports {
        html.required = true
        xml.required = true
        xml.outputLocation = file("${buildDir}/reports/jacoco/report.xml")
        csv.required = false
    }
}


def getResolvedArtifacts(Set<ResolvedArtifact> artifacts) {
    Set<String> resolvedArtifacts = [] as Set
    artifacts.each {
        // add current artifact
        resolvedArtifacts << "${it.moduleGroup}:${it.moduleName}:${it.moduleVersion}"

        // recursion to add children
        resolvedArtifacts += getResolvedArtifacts(it.children)
    }
    return resolvedArtifacts
}

// the configuration of the subprojects is located in the file referenced below
apply from: 'projects.gradle'
