// This file contains the configuration of all subprojects.
//
// The libraries, i.e. the definition of external dependencies
// (group, artifact, version) are located in gradle/libs.versions.toml
//
// Be aware that subprojects must also be specified in settings.gradle!
// Otherwise Gradle won't pick them up!

project(':org.adealsystems.platform.time') {
    description = "Time-related code"
    dependencies {
        implementation rootProject.libs.commons.text
    }
}

project(':org.adealsystems.platform.http') {
    description = "HTTP client/tools related code"
    dependencies {
        implementation rootProject.libs.commons.text
        implementation rootProject.libs.jackson.databind
        implementation rootProject.libs.httpclient
    }
}

project(':org.adealsystems.platform.id') {
    dependencies {
        implementation project(':org.adealsystems.platform.time')
    }
}

project(':org.adealsystems.platform.id.hadoop') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation rootProject.libs.hadoop.common
        testImplementation rootProject.libs.jcl.over.slf4j
    }
}

project(':org.adealsystems.platform.process') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
    }
}

project(':org.adealsystems.platform.io') {
    dependencies {
    }
}

project(':org.adealsystems.platform.io.transform') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
    }
}

project(':org.adealsystems.platform.io.test') {
    dependencies {
    }
}

project(':org.adealsystems.platform.io.compression') {
    dependencies {
        implementation rootProject.libs.commons.compress
        implementation rootProject.libs.snappy
    }
}

project(':org.adealsystems.platform.io.line') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
    }
}

project(':org.adealsystems.platform.io.csv') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation rootProject.libs.commons.csv
        implementation rootProject.libs.commons.io
        testImplementation project(':org.adealsystems.platform.io.test')
    }
}

project(':org.adealsystems.platform.io.json') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation project(':org.adealsystems.platform.io.line')
        implementation rootProject.libs.jackson.databind
    }
}

project(':org.adealsystems.platform.io.avro') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation rootProject.libs.avro
        testImplementation project(':org.adealsystems.platform.io.test')
        testRuntimeOnly rootProject.libs.snappy // optional snappy codec dependency
        testRuntimeOnly rootProject.libs.xz // optional xz codec dependency
        testRuntimeOnly rootProject.libs.zstd // optional zstandard codec dependency
    }
}

project(':org.adealsystems.platform.io.parquet') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation rootProject.libs.avro
        implementation rootProject.libs.hadoop.common
        implementation rootProject.libs.parquet.avro
        testImplementation project(':org.adealsystems.platform.io.test')
        testImplementation rootProject.libs.hadoop.minicluster
        testImplementation rootProject.libs.hadoop.hdfs
        testRuntimeOnly rootProject.libs.snappy // optional snappy codec dependency
        testRuntimeOnly rootProject.libs.xz // optional xz codec dependency
        testRuntimeOnly rootProject.libs.zstd // optional zstandard codec dependency
    }
}

project(':org.adealsystems.platform.state') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation rootProject.libs.jackson.databind
    }
}

project(':org.adealsystems.platform.queue') {
    description = "Queue-related code"
    dependencies {
        implementation rootProject.libs.commons.text
    }
}

project(':org.adealsystems.platform.queue.aws') {
    description = "Queue-related code"
    dependencies {
        implementation project(':org.adealsystems.platform.queue')
        implementation rootProject.libs.aws.sdk.sqs
        implementation rootProject.libs.commons.text
    }
}

project(':org.adealsystems.platform.spark.test') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.process')
        implementation rootProject.libs.spark.core
        implementation rootProject.libs.spark.sql // for SparkSession m(
        implementation rootProject.libs.junit.jupiter.api
        implementation rootProject.libs.spock.core
    }
}

project(':org.adealsystems.platform.spark') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.process')
        compileOnly rootProject.libs.spark.core
        compileOnly rootProject.libs.spark.sql // for SparkSession m(
        testImplementation rootProject.libs.spark.sql // for SparkSession m(
        testImplementation project(':org.adealsystems.platform.spark.test')
    }
}

project(':org.adealsystems.platform.spark.udf') {
    dependencies {
        implementation project(':org.adealsystems.platform.time')
        compileOnly rootProject.libs.spark.sql
        testImplementation rootProject.libs.spark.sql
    }
}

project(':org.adealsystems.platform.spark.main') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.time')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.spark')
        implementation rootProject.libs.spring.context
        compileOnly rootProject.libs.spark.core
        compileOnly rootProject.libs.spark.sql // for SparkSession m(
    }
}

project(':org.adealsystems.platform.spark.example') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.spark')
        implementation project(':org.adealsystems.platform.spark.udf')
        compileOnly rootProject.libs.spark.core
        compileOnly rootProject.libs.spark.sql // for SparkSession m(
        testImplementation project(':org.adealsystems.platform.spark.test')
        testImplementation rootProject.libs.spark.sql // for SparkSession m(
    }
}

project(':org.adealsystems.platform.spark.config.example') {
    dependencies {
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.spark')
        implementation project(':org.adealsystems.platform.spark.example')
        implementation rootProject.libs.spring.context
    }
}

project(':org.adealsystems.platform.spark.app.example') {
    apply plugin: 'application'
    apply plugin: 'com.gorylenko.gradle-git-properties'
    apply plugin: 'com.gradleup.shadow'

    gitProperties {
        gitPropertiesName = 'adeal-platform-git.properties'
        keys = ['git.dirty', 'git.commit.id', 'git.commit.id.abbrev', 'git.commit.time']
        customProperty 'build.name', { project.name }
        customProperty 'build.version', { project.version }
    }

    configurations {
        // see https://stackoverflow.com/questions/51048644/exclude-a-specific-dependency-from-springboots-bootjar-gradle-task/51109759
        runtimeExcludedFromBootJar
        runtime.extendsFrom runtimeExcludedFromBootJar
    }

    application {
        mainClass.set("org.adealsystems.platform.spark.main.Application")
    }

    dependencies {
        runtimeOnly project(':org.adealsystems.platform.spark.main')
        runtimeOnly project(':org.adealsystems.platform.spark.config.example')
        runtimeExcludedFromBootJar rootProject.libs.spark.core
        runtimeExcludedFromBootJar rootProject.libs.spark.sql // for SparkSession m(
        runtimeOnly 'org.codehaus.janino:janino:3.0.9' // Spark sucks
        runtimeOnly 'org.codehaus.janino:commons-compiler:3.0.9' // Spark sucks
    }

    def firstLevelProvided = project.configurations.runtimeExcludedFromBootJar.getResolvedConfiguration().getFirstLevelModuleDependencies()
    def artifactsToExclude = rootProject.getResolvedArtifacts(firstLevelProvided)
    artifactsToExclude.each { artifact ->
        project.logger.info "Excluding ${artifact} from being bundled into the shadow jar."
        shadowJar {
            dependencies {
                exclude(dependency(artifact))
            }
        }
    }

    tasks.named('shadowJar') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }

    // javadoc: error - No public or protected classes found to document.
    // 1 error
    // seinfeld.gif
    javadoc.enabled = false

    // disable anything we don't actually need.
    distZip.enabled = false
    distTar.enabled = false
    shadowDistZip.enabled = false
    shadowDistTar.enabled = false
    //jar.enabled = false
    sourcesJar.enabled = false
    javadocJar.enabled = false
}

project(':org.adealsystems.platform.webcollector') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation rootProject.libs.httpclient
        runtimeOnly rootProject.libs.httpcore
        testImplementation rootProject.libs.jackson.databind
        testRuntimeOnly rootProject.libs.logback.classic
        testRuntimeOnly rootProject.libs.jcl.over.slf4j
    }
}

project(':org.adealsystems.platform.sqlcollector') {
    dependencies {
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.csv')

        implementation project(':org.adealsystems.platform.time')
        implementation project(':org.adealsystems.platform.state')

        implementation rootProject.libs.commons.csv
        implementation rootProject.libs.jackson.annotations
        testRuntimeOnly rootProject.libs.logback.classic
        testRuntimeOnly rootProject.libs.jcl.over.slf4j
    }
}

project(':org.adealsystems.platform.orchestrator.core') {
    dependencies {
        implementation 'javax.xml.bind:jaxb-api:2.2.11' // outdated but necessary
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation project(':org.adealsystems.platform.io.json')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.state')

        implementation rootProject.libs.sulky.ulid
        implementation rootProject.libs.commons.lang
        implementation rootProject.libs.spring.context
        implementation rootProject.libs.jackson.datatype.jsr310
    }
}

project(':org.adealsystems.platform.orchestrator.executor') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation project(':org.adealsystems.platform.io.json')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.state')
        implementation project(':org.adealsystems.platform.orchestrator.core')

        implementation 'javax.xml.bind:jaxb-api:2.2.11' // outdated but necessary

        implementation rootProject.libs.sulky.ulid
        implementation rootProject.libs.commons.lang
        implementation rootProject.libs.jackson.datatype.jsr310
    }
}

project(':org.adealsystems.platform.orchestrator.executor.aws') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation project(':org.adealsystems.platform.io.json')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.state')
        implementation project(':org.adealsystems.platform.orchestrator.executor')
        implementation project(':org.adealsystems.platform.orchestrator.core')

        implementation 'javax.xml.bind:jaxb-api:2.2.11' // outdated but necessary

        implementation rootProject.libs.aws.sdk.sns
        implementation rootProject.libs.aws.sdk.sqs
        implementation rootProject.libs.aws.sdk.s3
        implementation rootProject.libs.aws.sdk.sfn
        implementation rootProject.libs.commons.lang
        implementation rootProject.libs.spring.context
        implementation rootProject.libs.jackson.datatype.jsr310
    }
}

project(':org.adealsystems.platform.orchestrator.executor.jenkins') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation project(':org.adealsystems.platform.io.json')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.state')
        implementation project(':org.adealsystems.platform.orchestrator.executor')
        implementation project(':org.adealsystems.platform.orchestrator.core')

        implementation 'javax.xml.bind:jaxb-api:2.2.11' // outdated but necessary

        implementation rootProject.libs.commons.lang
        implementation rootProject.libs.jackson.datatype.jsr310
    }
}

project(':org.adealsystems.platform.orchestrator.engine') {
    dependencies {
        implementation project(':org.adealsystems.platform.id')
        implementation project(':org.adealsystems.platform.io')
        implementation project(':org.adealsystems.platform.io.compression')
        implementation project(':org.adealsystems.platform.io.json')
        implementation project(':org.adealsystems.platform.process')
        implementation project(':org.adealsystems.platform.state')
        implementation project(':org.adealsystems.platform.orchestrator.executor')
        implementation project(':org.adealsystems.platform.orchestrator.executor.jenkins')
        implementation project(':org.adealsystems.platform.orchestrator.core')

        implementation 'javax.xml.bind:jaxb-api:2.2.11' // outdated but necessary

        implementation rootProject.libs.spring.boot.starter.actuator, {
            exclude group: 'org.springframework.boot', module: 'spring-boot-starter'
        }
        implementation rootProject.libs.spring.boot.starter.web, {
            exclude group: 'org.springframework.boot', module: 'spring-boot-starter'
        }
        implementation rootProject.libs.spring.boot.starter.thymeleaf, {
            exclude group: 'org.springframework.boot', module: 'spring-boot-starter'
        }
//        implementation libs.spring.boot.starter.quartz, {
//            exclude group: 'org.springframework.boot', module: 'spring-boot-starter'
//            exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
//        }

        implementation rootProject.libs.sulky.ulid
        implementation rootProject.libs.aws.sdk.sns
        implementation rootProject.libs.aws.sdk.sqs
        implementation rootProject.libs.aws.sdk.s3
        implementation rootProject.libs.commons.lang
        implementation rootProject.libs.spring.context
        implementation rootProject.libs.jackson.datatype.jsr310
    }
}

//project(':org.adealsystems.platform.orchestrator.app.example') {
//    dependencies {
//    }
//}
